name: restore-nerves-downloads
description: Restore the cached Nerves downloads

runs:
  using: composite
  steps:
    - name: Restore Nerves downloads
      uses: actions/cache/restore@v4
      with:
        path: ~/.nerves/dl
        key: nerves-dl-${{ github.ref_name }}-${{ github.sha }}
        restore-keys: |
          nerves-dl-${{ github.ref_name }}-
          nerves-dl- 