name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Firmware
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Patch Nerves
        run: ./.github/workflows/patch-nerves.sh
      - uses: ./.actions/setup-beam-nerves
        with:
          otp-version: 26.2.1
          elixir-version: 1.16.1
          nerves-bootstrap-version: 1.11.6
      - uses: ./.actions/get-br-dependencies
      - uses: ./.actions/build-system
